version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.6.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run:
          name: Lint
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml

      - run:
          name: Test
          command: yarn test --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-jest-results.xml"

      # - run:
      #     - name: Merge Junit Results
      #     - command: npx junit-merge -d reports/junit -o reports/junit/merged-results.xml

      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit